/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditWrapper: typeof import('./src/components/EditWrapper.vue')['default']
    LeftTemplate: typeof import('./src/components/LeftTemplate.vue')['default']
    PropsForm: typeof import('./src/components/PropsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./src/components/Text.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
